version: "3.6"

services:
  dev-container:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:12

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
