version: '3.6'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-12}
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

  graphql-engine:
    image: hasura/graphql-engine:${HASURA_GRAPHQL_IMAGE_VERSION:-latest}
    restart: always
    ports:
      - "${HASURA_GRAPHQL_PORT:-8080}:8080"
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET:-secret}
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${HASURA_GRAPHQL_DATABASE_NAME:-postgres}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE:-false}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES:-startup,http-log,webhook-log,websocket-log,query-log}

volumes:
  db_data:
