version: '3.6'

services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}

  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    restart: always
    ports:
      - "8181:8080"
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}

volumes:
  db_data:

