version: '3.6'

services:
  dev-container:
    image: mdwagner/next-great-idea:latest
    depends_on:
      - postgres
      - graphql-engine
      - fusionauth
    links:
      - postgres
      - "graphql-engine:hasura"
      - fusionauth

  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  graphql-engine:
    image: hasura/graphql-engine:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,webhook-log,websocket-log,query-log

  fusionauth:
    image: fusionauth/fusionauth-app:1.16.1
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/fusionauth
      DATABASE_ROOT_USER: postgres
      DATABASE_ROOT_PASSWORD: password
      DATABASE_USER: fusionauth
      DATABASE_PASSWORD: password
      FUSIONAUTH_MEMORY: 512M
      FUSIONAUTH_SEARCH_ENGINE_TYPE: database
      FUSIONAUTH_URL: http://fusionauth:9011
      FUSIONAUTH_RUNTIME_MODE: development
      FUSIONAUTH_KICKSTART: /kickstart/kickstart_dev.json
    restart: always
    ports:
      - 9011:9011
    volumes:
      - /usr/local/fusionauth/config
      - ./fusionauth:/kickstart

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
