#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

source crystal_server/script/helpers/text_helpers

notice "Running System Check"
./crystal_server/script/system_check
print_done

notice "Installing shards"
shards install | indent

if [ ! -f ".env" ]; then
  notice "No .env found. Creating one."
  touch .env
  print_done
fi

print_done
notice "Run 'lucky dev' to start the app"
