name: Docker CI

on:
  push:
    paths:
    - 'Dockerfile'

env:
  IMAGE_NAME: mdwagner/next-great-idea

jobs:
  build:
    name: Build and Push branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag docker image
        run: docker build -f Dockerfile -t $IMAGE_NAME:${GITHUB_REF#refs/heads/} .

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_NAME:${GITHUB_REF#refs/heads/}

      - name: Push image as latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag $IMAGE_NAME:${GITHUB_REF#refs/heads/} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
