name: Docker CI

on:
  push:
    paths:
    - 'Dockerfile'

env:
  IMAGE_NAME: mdwagner/next-great-idea
  VERSION: latest

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build . --file Dockerfile

  push:
    name: Push image to docker-hub
    runs-on: ubuntu-latest

    needs:
      - build

    if: github.ref == 'ref/head/master'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:$VERSION

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_NAME:$VERSION
