name: Docker CI

on:
  push:
    paths:
    - 'Dockerfile'

jobs:
  push:
    name: Push Docker image
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true

      - name: Push to Github Container Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.GHCR_PAT_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true
